// Generated by CoffeeScript 1.3.3

exports.attach = function() {
  this.addModule('http', 'request');
  return this.helpers['http'] = function(url, cb) {
    return data.http(url, {
      json: 'true'
    }, cb);
  };
};
